### ISSUE TITLE
Issue at using Angular Material Styles.

### ISSUE THREAD

**Issue by frankdavidcorona** [jvandemo/generator-angular2-library#251]
I'm did a library that use [Angular Material](https://material.angular.io/guide/getting-started), but when I test the library don't recognize styles of material, here it's my code:
`styleUrls: [
    'sample.component.css'
  ]
`
And import the prebuilt theme for Material:
`@import '../node_modules/@angular/material/prebuilt-themes/indigo-pink.css';`

When I test my library some styles are missing.

**Comment by caroso1222** [comment]
Without digging too much, it seems to me that those styles imported in `sample.component.css` will just get encapsulated by the component. That's why [Material explicitly asks](https://material.angular.io/guide/theming) to import the theme in the main `style.css` file of the project. 

I think the solution to this issue is just to import the theme in the consuming application, inside `style.css`. If you don't like asking your users to do that, you can always follow [the recommended approach](https://github.com/jvandemo/generator-angular2-library/blob/master/guides/import_non_angular_libraries.md#importing-css-provided-by-3rd-party-library) to expose third party css files from your library.

**Comment by izifortune** [comment]
Thanks @caroso1222 I will close this issue as answered.
