### ISSUE TITLE
[ts] Experimental support for decorators error

### ISSUE THREAD

**Issue by caroso1222** [jvandemo/generator-angular2-library#47]
**Repro steps:**
1. Scaffold an app running `yo angular2-library`
2. Open it in vscode
3. Add file `hello.component.ts`
4. Add this into the file:
```javascript
import { Component } from '@angular/core';

@Component({
  selector: 'app-hello',
  template: `<h1>Hello World</h1>`
})
export class HelloComponent {
  title = 'app works!';
}
```

**Error**
At this point, TypeScript will underline `HelloComponent` complaining about this: 
```bash
[ts] Experimental support for decorators is a feature that is subject to change in future release. Set the 'experimentalDecorators' option to remove this warning
```

The `"experimentalDecorators"` flag is set to `true` in `tsconfig.json`, but the error is still showing up. Any idea on how to fix this?

**Comment by jdjuan** [comment]
Hey @caroso1222 !, I went through the same a few days ago. It turns out that your editor will pop compiling errors based on the `tsconfig.json` file. This generator provides a configuration in which it will just apply that configuration to the `index.ts` file. What you want to do is to reference all the other files included in the `src` folder as well. To do so, just add this to your `tsconfig.json` file:

```
"include": [
    "src/**/*.ts"
  ],
```

This way `experimentalDecorators` will also work in your `hello.component.ts`. Changes won't be reflected right away, you want to re-open the file.

**Comment by caroso1222** [comment]
Thank you @jdjuan! Works like a charm. Now, take a look at the `tscongif.json` [docs](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html). If you get rid of `include` and `files`, it will compile all `*.ts` by default excluding whatever is set in `exclude`. So, according to this, in my opinion, a cleaner approach would be to remove `include` and `files` from `tsconfig.json`, just like `angular-cli` does. Try it and if it works and makes sense to you, you can go ahead and modify your PR with this.

**Comment by jdjuan** [comment]
Makes sense to me! Just did. Thanks for the heads up

**Comment by jvandemo** [comment]
@jdjuan, @caroso1222 &mdash; Thank you both, much appreciated!

PR has been merged 👍
