### ISSUE TITLE
How to serve?

### ISSUE THREAD

**Issue by FanYeeChok** [jvandemo/generator-angular2-library#55]
Hi,

I'm getting this error. How to do the development from this project?

Using ng serve cause the error. Any other alternative way?
```
bash-3.2$ ng serve
You have to be inside an angular-cli project in order to use the serve command.
```

**Comment by caroso1222** [comment]
@FanYeeChok `ng serve` is throwing error because this is not an angular-cli project.

What you can do is to rely on `npm link` to use your library in a cli project.

Try this:

1. Create app with generator: `yo angular2-library`. Let's say you go with name `ngx-library`.
2. Eventhough the dist folder is generated, go ahead and transpile files again: `npm run tsc`
3. Create a new Angular app. Let's assume you use angular-cli. `ng new hello-world`
4. Run `npm link` inside `/ngx-library`, and `npm link ngx-library` inside `/hello-world` to have your library available inside your Angular app `node_modules` folder.
5. Import your new `SampleModule` module into `app.module` (add to decorator imports as well). If you have problems when running ng serve, try adding the library to decorator as `SampleModule.forRoot()`.
6. Create `<sample-component></sample-component>` in app.component.html. Run `ng serve`. It should show an h1 with text "Sample Component". Our library is working.

@jvandemo what do you think about adding to README these or some other indications on how to use the `yo` library in development?

**Comment by FanYeeChok** [comment]
Thanks @caroso1222 for quick reply. Will give it a try.

**Comment by jvandemo** [comment]
@caroso1222 &mdash; Thank you, I have added an extra section to the README.

I really appreciate you helping out others with this generator by formulating your structured answers.

Thank you, much appreciated!! 👍

**Comment by jvandemo** [comment]
@FanYeeChok &mdash; Can you let us know how it goes? Thank you!

**Comment by FanYeeChok** [comment]
@jvandemo 
Yup. It's working fine now. Just every time if any changes on `ngx-library` and need to execute `npm run tsc`. If got any hot deploy/watch will be better.

Now i moved all the code to the project `hello-world` for development. If everything work fine, only move back to `ngx-library` and to the final test.

At the `app.module` has to import as `SampleModule.forRoot()` only worked.

**Comment by jvandemo** [comment]
@FanYeeChok &mdash; Thank you for the confirmation 👍
