### ISSUE TITLE
ES5 ts build index.js keep import

### ISSUE THREAD

**Issue by gaetansenn** [jvandemo/generator-angular2-library#67]
Hi,

The current build of the generator is currently keeping the import inclusion (es6) in the index.js but the webpack of my angular 4 project is not converting the libraries into es5 and if I change the tsconfig.es5.json module to commonjs I don't have all the .ts files into the index.js.

Do you have a solution for that ?

Regards,

Gaetan SENN

**Comment by jvandemo** [comment]
The code in `dist` will use `import` and `export` statements, but it is ES5 code, because that is what Webpack requires.

The `module` key in `src/tsconfig.es5.json` is set to `module`, which tells the compiler to output `import` and `export` statements.

The `target` key in `src/tsconfig.es5.json` is set to `es5`, which tells the compiler to ouput ES5 code.

Those are the settings that are recommended by the official guidelines and Webpack should be able to handle the file in `dist` correctly.

Is it not working? Are you seeing an error? Thanks!

**Comment by jvandemo** [comment]
Closed due to lack of response. Feel free to re-open if needed. Thanks!
