### ISSUE TITLE
Support (or document) projects that use lerna

### ISSUE THREAD

**Issue by mattnathan** [jvandemo/generator-angular2-library#86]
[Lerna](https://github.com/lerna/lerna) is awesome and allows us to create reusable components across a suite of angular applications without all the overhead of repository and version management.

It would be great if this generator could be updated to support the patterns supported by lerna, specifically linking at the root package level.

Currently I think this involves either modifications to the root `package.json` to reference the `src` or `dist` folder or the addition of an `index.ts` in the root folder so that you can link the root folder instead of needing to link either the `dist` or `src` folders depending on your use case.

**Comment by jvandemo** [comment]
@mattnathan &mdash; Would you be interested in writing a guide for people that wish to use the Lerna guidelines in an Angular library?

Thank you for your feedback!

**Comment by mattnathan** [comment]
@jvandemo After a few hours trying different combinations of settings for the `package.json` I was unable to come up with a solution to this that solved the issue without a fairly major workaround.

Effectively Lerna assumes that if it finds a `package.json` then that is the project and location where publishing/versioning/running/linking should happen. Unfortunately this is incompatible with the way this generator works where these concerns are expected to be run from different locations within the project. My understanding is that

 * publishing- happen from `dist/package.json`
 * running - happen from the root `package.json`
 * linking - depending on the compiled vs .ts requirement either `src/package.json` or `dist/package.json`
 * versioning - happens in `src/package.json`
 * app dependencies - not entirely sure where this should be yet

For my case (and because this is the best generator I've found for ng libs so far) I've configured Lerna to do all operations on the `src/package.json` (using `"packages": ["components/**/src"]` in `lerna.json`) and will have to add tooling to support publishing/etc that is more aware of this generators structure.

If I come up with a better solution that satisfies more of the use-cases than just linking then I'd be happy to write a guide if that's still something you want me to do.

**Comment by jdjuan** [comment]
Thanks @mattnathan for this research! I never heard of Lerna before, now I am diving into it 💪 

### Do we need two package.json after all? 🤔 🤔 

@jvandemo now that @mattnathan mentions it, do we have a strong reason to have two `package.json`? Technically we could use just one, it would force our users to install `devDependencies` even when they just want to use the library (not develop over it), but that wouldn't be much of a problem since it would still be local. In general terms one `package.json` is simpler than two. What do you think?

### What is each package.json? FYI: @mattnathan 

- `root/package.json`: Used for development, has the devDependencies needed to develop the library.
- `dist/package.json`: Used for publishing. It has the dependencies for production.
- `src/package.json`: This is just the package that is copied and pasted to the `dist` folder

**Comment by abalad** [comment]
I'm also interested in this implementation, I did some testing to create this and nothing

**Comment by jvandemo** [comment]
@mattnathan &mdash; Thank you very much. If you manage to get the tooling to work, then yes, I would be happy to include your guide on the WIKI page 👍 

@jdjuan &mdash; Using separate `package.json` is currently officially recommended by the Angular team. To keep this generator aligned with the official recommendations, let's keep them separeted 👍 

I will close this issue for now. If you feel anything needs to be added, feel free to re-open it.

Thanks again for all your great work and input, much appreciated!
