### ISSUE TITLE
How to debug the .ts files from the dist folder

### ISSUE THREAD

**Issue by abalad** [jvandemo/generator-angular2-library#96]
Someone has some idea how to access the files in the dist folder in debug mode in Chrome (Developer Tools), because only the index.js file appears with everything that was created, but I wanted to have view and debug the file TS.

**Comment by rtrompier** [comment]
+1.

How to get .ts file in chrome debugger when linked from a angular-cli app ?

**Comment by jvandemo** [comment]
From your library directory, link the `src` directory instead of the `dist` directory as outlined here: https://github.com/jvandemo/generator-angular2-library#how-can-i-avoid-recompilation-during-development.

This should give you access to the entire TypeScript source files in chrome DevTools:
![debugger](https://cloud.githubusercontent.com/assets/1859381/26282090/2c458b90-3e0a-11e7-944f-e200a98bb9dc.png)

While this is convenient, don't forget to link the `dist` directory again (instead of `src`)  so you can verify whether your library files in `dist` work as expected before you publish them.

Can you please confirm if this works for you? Thanks in advance!

**Comment by jvandemo** [comment]
Closed due to lack of response. Feel free to re-open if needed. Thanks!
